name: Auto Export & Deploy Godot Web Game

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Godot
      uses: Yukitty/godot-ci@v4
      with:
        version: "4.1"
        export-templates: true

    - name: Export Game for Web
      run: |
        mkdir -p export/web
        godot --headless --export-release "Web" export/web/index.html

    - name: Upload Web Export
      uses: actions/upload-pages-artifact@v2
      with:
        path: export/web

  deploy:
    runs-on: ubuntu-latest
    needs: export
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
