name: Godot Export and Deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: '4.1.0'  # Specify your Godot version
          export_templates: true

      - name: Export Project
        run: |
          mkdir -p export/web
          godot --headless --export-release "Web" export/web/index.html

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./export/web
