name: Godot Export and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: "4.4.0"
          use-dotnet: false
          include-templates: true

      - name: Export Project for Web
        run: |
          mkdir -p export/web
          godot --headless --export-release "Web" export/web/index.html

      - name: Upload Web Export for Deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: export/web
          name: github-pages

      - name: List Directory Contents
        run: |
          echo "Current directory structure:"
          ls -la
          tree -L 2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Artifact # Add this step to fetch the built project
        uses: actions/download-artifact@v3
        with:
          name: github-pages # Ensure this matches the artifact name from the build job
          path: ./artifact # Define where it should be extracted

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_path: ./artifact # Deploy the downloaded artifact
